export const data = [
  {
    provider: 'github',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
  {
    provider: 'gitlab',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
  {
    provider: 'google',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
  {
    provider: 'generic_oauth',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
  {
    provider: 'grafana',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
  {
    provider: 'azuread',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
  {
    provider: 'okta',
    settings: {
      allow_assign_grafana_admin: false,
      allow_sign_up: true,
      allowed_domains: '',
      allowed_groups: '',
      api_url: '',
      auth_url: '',
      auto_login: false,
      client_id: '',
      client_secret: '',
      email_attribute_name: '',
      email_attribute_path: '',
      enabled: false,
      groups_attribute_path: '',
      hosted_domain: '',
      icon: '',
      name: 'default name',
      role_attribute_path: '',
      role_attribute_strict: false,
      scopes: '',
      team_ids_attribute_path: '',
      teams_url: '',
      tls_client_ca: '',
      tls_client_cert: '',
      tls_client_key: '',
      tls_skip_verify_insecure: false,
      token_url: '',
      use_pkce: true,
      use_refresh_token: false,
    },
    source: 'system',
  },
];

export const formattedData = data.map((entry) => {
  const provider = entry.provider.replace(/_/g, ' '); // Replace underscores with spaces
  const prettyName = provider.charAt(0).toUpperCase() + provider.slice(1);
  return { name: prettyName, ...entry };
});
