---
kind: pipeline
name: saga-docs

trigger:
  event:
    include:
      - pull_request
      - push
      - tag

platform:
  os: linux
  arch: amd64

steps:
  - name: Install dependencies and build
    image: node:18-alpine
    commands:
      - yarn install
      - yarn build
---
kind: signature
hmac: 5cf7ae4c8af697ef624610f6bf42665632be9e7fdbf88ed1c134fcd96bf834b2
