---
kind: pipeline
name: saga-docs

trigger:
  event:
    include:
      - pull_request
      - push
      - tag

platform:
  os: linux
  arch: amd64

steps:
  - name: Install dependencies and build
    image: node:16-alpine
    commands:
      - yarn install
      - yarn build
---
kind: pipeline
type: docker
name: Containerize
platform:
  os: linux
  arch: amd64
trigger:
  event:
    - push
    - tag
  ref:
    - refs/heads/main
    - refs/tags/v*

steps:
  - name: build and push
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --update --no-cache make git coreutils
      - make push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: signature
hmac: bc506bc893dc793c4e30bbba5ee43114c77f37c00e6a88e611deef64406ca3e2
