export const ComponentsStatusInfo = [
  {
    componentName: 'Alert',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Badge',
    figmaStatus: 'in-progress',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Button',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Card',
    figmaStatus: 'in-progress',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Checkbox',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Field',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'FileDropzone',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'FilterPill',
    figmaStatus: 'to-do',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'IconButton',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'InlineField',
    figmaStatus: 'planned',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Input',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'InteractiveTable',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Modal',
    figmaStatus: 'to-do',
    storybookStatus: 'to-do',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Pagination',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'PluginSignature',
    figmaStatus: 'to-do',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'RadioButtonGroup',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'RadioButtonList',
    figmaStatus: 'to-do',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Switch',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Text',
    figmaStatus: 'to-do',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'TextArea',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'TextLink',
    figmaStatus: 'to-do',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'ToggleTip',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
  {
    componentName: 'Tooltip',
    figmaStatus: 'ready-to-use',
    storybookStatus: 'ready-to-use',
    sagaStatus: 'ready-to-use',
  },
];
