export const ComponentsStatusInfo = [
  {
    componentName: 'Alert',
    generalStatus: 'n-a',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Badge',
    generalStatus: 'in-progress',
    figmaStatus: 'in-progress',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Button',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Card',
    generalStatus: 'in-progress',
    figmaStatus: 'in-progress',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Checkbox',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Field',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'FileDropzone',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'FilterPill',
    generalStatus: 'in-progress',
    figmaStatus: 'to-do',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'IconButton',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'InlineField',
    generalStatus: 'planned',
    figmaStatus: 'planned',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Input',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'InteractiveTable',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Modal',
    generalStatus: 'to-do',
    figmaStatus: 'to-do',
    storybookStatus: 'to-do',
    sagaStatus: 'done',
  },
  {
    componentName: 'Pagination',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'PluginSignature',
    generalStatus: 'to-do',
    figmaStatus: 'to-do',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'RadioButtonGroup',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'RadioButtonList',
    generalStatus: 'to-do',
    figmaStatus: 'to-do',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Switch',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Text',
    generalStatus: 'n-a',
    figmaStatus: 'to-do',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'TextArea',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'TextLink',
    generalStatus: 'n-a',
    figmaStatus: 'to-do',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'ToggleTip',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
  {
    componentName: 'Tooltip',
    generalStatus: 'done',
    figmaStatus: 'done',
    storybookStatus: 'done',
    sagaStatus: 'done',
  },
];
