export const ComponentsStatusInfo = [
  {
    componentName: 'Alert',
    generalStatus: 'N/A',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Badge',
    generalStatus: 'In Progress',
    figmaStatus: 'In Progress',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Button',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Card',
    generalStatus: 'In Progress',
    figmaStatus: 'In Progress',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Checkbox',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Field',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'FileDropzone',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'FilterPill',
    generalStatus: 'In Progress',
    figmaStatus: 'To Do',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'IconButton',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'InlineField',
    generalStatus: 'Planned',
    figmaStatus: 'Planned',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Input',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'InteractiveTable',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Modal',
    generalStatus: 'To Do',
    figmaStatus: 'To Do',
    storybookStatus: 'To Do',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Pagination',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'PluginSignature',
    generalStatus: 'To Do',
    figmaStatus: 'To Do',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'RadioButtonGroup',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'RadioButtonList',
    generalStatus: 'To Do',
    figmaStatus: 'To Do',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Switch',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Text',
    generalStatus: 'N/A',
    figmaStatus: 'To Do',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'TextArea',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'TextLink',
    generalStatus: 'N/A',
    figmaStatus: 'To Do',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'ToggleTip',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
  {
    componentName: 'Tooltip',
    generalStatus: 'Done',
    figmaStatus: 'Done',
    storybookStatus: 'Done',
    sagaStatus: 'Done',
  },
];
