name: Create Tokens
on:
  push:
    paths:
      - 'tokens/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for git-auto-commit-action

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      # Install dependencies
      - run: npm install
      # Transform Figma Tokens JSON to something Style Dictionary can read, run Style Dictionary
      - run: npm run build:tokens
      # Add files that were created during a run, e.g. created files from style dictionary or token-transformer.
      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
        with:
          branch: hackathon_tokens
          commit_message: Update Tokens
