name: Deploy to Developer Portal PROD Bucket

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy docs to Developer Portal Bucket
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Build documentation website
        run: yarn build --config docusaurus.config.js

      - id: 'auth'
        uses: 'google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a'

      - name: 'Deploy to Developer Portal Bucket'
        run: |
          gsutil -m rsync -r -d -c ./build/ gs://grafana-developer-portal/saga
